---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: easypay-hpa
  namespace: easypay
  labels:
    app: easypay
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: easypay-app
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: v1
kind: Service
metadata:
  name: easypay-service
  namespace: easypay
spec:
  selector:
    app: easypay
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30050
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: easypay-app
  namespace: easypay
  labels:
      app: easypay
      role: frontend
spec:
  selector:
    matchLabels:
      app: easypay
      role: frontend
  template:
    metadata:
      labels:
        app: easypay
        role: frontend
    spec:
      initContainers:
        - image: busybox:1.28
          name: wait-db
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: easypay-config
                  key: DB_HOST
          command:
            - sh
            - -c
            - |
              until nslookup ${DB_HOST};
              do
                echo waiting for ${DB_HOST};
                sleep 3;
              done
      containers:
        - name: easypay
          image: "983162875680.dkr.ecr.us-east-1.amazonaws.com/easypay-repo:latest"
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: easypay-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: easypay-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: easypay-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: easypay-secrets
                  key: mysql-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: easypay-secrets
                  key: mysql-pwd
          ports:
            - name: http
              containerPort: 30050
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi

